fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener: true
  view:
    view_response_listener:
      enabled:              true
      force:                false
      service:              null
    formats:
      xml: true
      json : true
    templating_formats:
      html: true
    force_redirects:
      html: true
    failed_validation: HTTP_BAD_REQUEST
    default_engine: twig
  routing_loader:
    default_format: json
  serializer:
    serialize_null: true
  exception:
    enabled: true