old_sound_rabbit_mq:
  connections:
    default:
      host:     'localhost'
      port:     5672
      user:     'guest'
      password: 'guest'
      vhost:    '/'
      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3
      keepalive: false
      heartbeat: 0
      use_socket: true
  producers:
    check_policy:
      connection:       default
      exchange_options: { name: 'notification.v1.check_policy', type: direct }

  consumers:
    check_policy:
      connection:       default
      exchange_options: { name: 'notification.v1.check_policy', type: direct }
      queue_options:    { name: 'notification.v1.check_policy' }
      callback:         app.consumer.check_policy