offers:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_

buy:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_

payment_receive:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_

policy:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_

policies:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_