offers:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_

buy:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_
  methods: [POST]

payment_receive:
  type: rest
  resource: App\Controller\ClientRestController
  name_prefix: api_
  methods: [POST]